apiVersion: apps/v1
kind: Deployment
metadata:
  name: deadbeefio-api-deployment
  labels:
    app: deadbeefio-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deadbeefio-api
  template:
    metadata:
      labels:
        app: deadbeefio-api
    spec:
      containers:
      - name: api
        image: deadbeefio_api
        env:
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_ADDR
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: host } }
        - name: DB_PORT
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: port } }
        - name: DB_NAME
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: dbname } }
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: user } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: password } }
        - name: GET_HOSTS_FROM
          value: dns
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: deadbeefio-api-service
  labels:
    app: deadbeefio-api
spec:
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: deadbeefio-api
