apiVersion: apps/v1
kind: Deployment
metadata:
  name: deadbeefio-app-deployment
  labels:
    app: deadbeefio-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deadbeefio-app
  template:
    metadata:
      labels:
        app: deadbeefio-app
    spec:
      containers:
      - name: deadbeefio-app
        image: deadbeefio_app_${BUILD_TYPE}
        imagePullPolicy: Never
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deadbeefio-app-service
  labels:
    app: deadbeefio-app
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: deadbeefio-app
