apiVersion: apps/v1
kind: Deployment
metadata:
  name: deadbeefio-dbadmin-deployment
  labels:
    app: deadbeefio-dbadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deadbeefio-dbadmin
  template:
    metadata:
      labels:
        app: deadbeefio-dbadmin
    spec:
      containers:
      - name: deadbeef-dbadmin
        image: rloop2:5000/deadbeefio/deadbeefio_dbadmin
        tty: true
        stdin: true
        env:
        - name: DB_ADDR
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: host } }
        - name: DB_PORT
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: port } }
        - name: DB_NAME
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: dbname } }
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: user } }
        - name: DB_PASSWORD_RAW
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: password } }
