apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  rules:
  - host: deadbeef.io
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: deadbeefio-api-service
            port:
              number: 4000
  - host: deadbeef.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deadbeefio-app-service
            port:
              number: 80
  tls:
  - hosts:
    - deadbeef.io
    secretName: deadbeef-cert
