apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: deadbeefio-api-service
            port:
              number: 4000
  - http:
      paths:
      - path: /.*
        pathType: Prefix
        backend:
          service:
            name: deadbeefio-app-service
            port:
              number: 80
